baseConfig: ./tsconfig.base.json
presets: 
  default: 
    compilerOptions: 
      rootDir: 'src'
      outDir: 'dist'
      incremental: true
      tsBuildInfoFile: 'dist/.tsbuildinfo'
    include:
      - src/**/*
    exclude: 
      - src/**.spec.ts
      - src/**.spec.tsx
  json: 
    include: 
      - 'src/**/*.json'
  esm: 
    compilerOptions:
      module: ESNext
      target: ESNext
      outDir: esm
      tsBuildInfoFile: 'esm/.tsbuildinfo'
  common:
    compilerOptions:             
      target: ES2015               
      module: CommonJS
      outDir: commonjs
      tsBuildInfoFile: 'common/.tsbuildinfo'
