# yaml-language-server: $schema=packages/config/schemas/root.json
baseConfig: ./tsconfig.base.json
mode: loose
presets: 
  default: 
    compilerOptions: 
      rootDir: 'src'
      outDir: 'dist'
      incremental: true
      tsBuildInfoFile: 'dist/.tsbuildinfo'
    include:
      - src/**/*
    exclude: 
      - src/**.spec.ts
      - src/**.spec.tsx
  json: 
    include: 
      - 'src/**/*.json'
  esm: 
    compilerOptions:
      module: ESNext
      target: ESNext
      outDir: esm
      tsBuildInfoFile: 'esm/.tsbuildinfo'
  common:
    compilerOptions:
      target: ES2015               
      module: CommonJS
      outDir: commonjs
      tsBuildInfoFile: 'commonjs/.tsbuildinfo'
  type:
    compilerOptions:
      outDir: types
      tsBuildInfoFile: 'types/.tsbuildinfo'
      emitDeclarationOnly: true


# files:
#   esm: 
#     preset: esm
#   common: 
#     preset: common
#   type: 
#     preset: type
#   default:
#     preset: default
