changesetIgnorePatterns:
  - "**/LICENSE"
  - "**/README.md"
  - .github/workflows/*

compressionLevel: mixed

enableGlobalCache: false

initFields:
  version: 0.1.0
  author:
    email: sabinmarcu@gmail.com
    name: Sabin Marcu
  license: MIT
  main: dist/index.js
  publishConfig:
    access: public
  typings: dist/index.d.ts

initScope: tscmono

npmAuthToken: "${YARN_NPM_AUTH_TOKEN:-NO_TOKEN}"

packageExtensions:
  "@babel/plugin-proposal-nullish-coalescing-operator@*":
    dependencies:
      "@babel/helper-plugin-utils": "*"
      "@babel/plugin-syntax-nullish-coalescing-operator": "*"
  gatsby-plugin-mdx@*:
    dependencies:
      "@emotion/react": "*"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
